services:
  backend:
    container_name: back-sv-users 
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - shared-net  # <- Conectado a red compartida

networks:
  shared-net:
    name: shared-net
